import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

  <html className="h-full">
    <body className="h-screen">

      <div className="overflow-hidden">
        {children}
      </div>  
    </body>
  </html>
  );
}
